backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under public/uploads
public_folder: "/img" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "product"
    identifier_field: name
    label: "Product"
    folder: "src/content/product"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Price", name: "price", widget: "number", valueType: "float", min: 0}
      - {label: "Description", name: "description", widget: "markdown"}